
const SHOW = (url, done = 0, name = undefined) => ({url, name, done});

// Data
tvData = [
  SHOW('http://www.tw116.com/occident/fuermosijibenyanyifadiwuji/', 4, 'Elementary V'),
  SHOW('http://www.tw116.com/occident/zuieheimingdandisiji/', 8, '罪恶黑名单'),
  SHOW('http://www.tw116.com/occident/tianxiedisanji/', 10, 'scopin III'), //# -1. e.g. 10 will block to 11
  SHOW('http://www.tw116.com/occident/shendunjutegongdisiji/', 8, 'shield IV'),
  SHOW('http://www.tw116.com/occident/mangdiandierji/', 9, 'Blind spot II'),
  SHOW('http://www.tw116.com/occident/jiexikaqiongsidiyiji/', 0, 'Jones'),
  SHOW('http://www.tw116.com/occident/lukekaiqidiyiji/', 1, 'Luke Cage'),
  SHOW('http://www.tw116.com/occident/shikongshouweikuashikongzhuibudiyiji/', 10, '時空守衛 Timeless'),
  SHOW('http://www.tw116.com/occident/tushuguanyuandierji/', 10, '圖書館員第二季'),
  SHOW('http://www.tw116.com/occident/xibushijiediyiji/', 10, 'West World'),
  SHOW('http://www.tw116.com/occident/tegongkatedierji/', 6, 'Agent carter'),
  SHOW('http://www.tw116.com/occident/Xdangandishiji/', 6, 'X File'),
  SHOW('http://www.tw116.com/occident/shierhouzidierji/', 13, '12 Monkeys'),
  SHOW('http://www.tw116.com/occident/bingyuhuozhigequanlideyouxidiliuji/' , 10, 'Game of Throne 6'),
  SHOW('http://www.tw116.com/occident/guaiqiwuyudiyiji/', 0, '怪奇物語'),
  //{id: "40555", name: "black mirror S1"},
  //{id: "50254", name: "black mirror S2"},
  SHOW('http://www.tw116.com/occident/heijingdisanji/', 0, 'black mirror S3'),
  SHOW('http://www.tw116.com/occident/shuishixiongshoudiyijiwomenzhizhongdiyiji/', 0, '誰是兇手'),
  SHOW('http://www.tw116.com/occident/shandianxiadiyiji/', 0 ,'Flash III'), 
  SHOW('http://www.tw116.com/occident/heikejuntuandiyiji/', 0, 'Mr. Robot'),
  SHOW('http://www.tw116.com/occident/xiaoyaofawaidiyiji/', 0, 'Get away with murder'),
  SHOW('http://www.tw116.com/occident/meiguokongbugushijixingxiumeiguoguaitandisiji/', 18, '美国恐怖故事：畸形秀'),
  SHOW('http://www.tw116.com/occident/meiguokongbugushidiwuji/', 0, '美国恐怖故事第五季'),
];

movieData = [
  SHOW('http://www.tw116.com/action/bianfuxiadazhanchaorenzhengyiliming/', 1),
  SHOW('http://www.tw116.com/drama/qihuansenlin/'),
  SHOW('http://www.tw116.com/fiction/Xzhanjingtianqi/'),
  SHOW('http://www.tw116.com/fiction/ailisimengyouxianjing2/'),
  SHOW('http://www.tw116.com/drama/jinqianguaishou/'),
  SHOW('http://www.tw116.com/horror/zhaohun2/', 1),
  SHOW('http://www.tw116.com/action/lieshendongrizhizhan/'),
  SHOW('http://www.tw116.com/fiction/chuimengjuren/'),
  SHOW('http://www.tw116.com/action/taishanguilaixianzhanconglin/'),
  SHOW('http://www.tw116.com/action/dieyingzhongzhong5/', 1),
  SHOW('http://www.tw116.com/comedy/zishaxiaodui/', 1),
  SHOW('http://www.tw116.com/anime/aichongdajimi/'),
  SHOW('http://www.tw116.com/action/fushanxingshisulieche/', 1),
  SHOW('http://www.tw116.com/action/lueduozhe/'),
  SHOW('http://www.tw116.com/horror/annahuatedeliqimingyun/', 1),
  SHOW('http://www.tw116.com/horror/shiti/'),
  SHOW('http://www.tw116.com/fiction/ID4xingjizhongsheng/', 1),
  SHOW('http://tw116.com/action/changchengwanlichangcheng/'),
  SHOW('http://tw116.com/action/youming/'),
  SHOW('http://tw116.com/action/jinganglang2/'),
  SHOW('http://tw116.com/action/mingxuanyixian/'),
  SHOW('http://tw116.com/action/anshayouxi/'),
  SHOW('http://tw116.com/action/morihuixuan/'),
  SHOW('http://tw116.com/action/yindiannabolisihaoyongzhewuju/'),
  SHOW('http://tw116.com/fiction/chaonengansidui/'),
  SHOW('http://tw116.com/fiction/renleiqingchujihua3/'),
  SHOW('http://tw116.com/horror/wumingnvshi/'),
  SHOW('http://tw116.com/horror/dandingmimadiyu/'),
  SHOW('http://tw116.com/horror/shatanjueshadao/'),
  SHOW('http://tw116.com/horror/huashenguimotong/'),
  SHOW('http://tw116.com/horror/fengchecanan/'),
  
];
